
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://hrish4bh.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: "" #/personal-jekyll-theme

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Hrishabh Kumar"
title: "Hrishabh Kumar"
description: "Blog and website of Hrishabh Kumar, blogging mainly for tech. Opinions expressed are mine."
keywords: "hrishabh, hrish4bh, personal, jekyll, theme"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

#background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Programmer, Tech Enthusiast, Explorer! "
  - text: "Never stop learning, The day you stopped, You are Dead!"

me-img: "/img/hrishabh.png"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "personal-jekyll-theme"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/tcs_logo.jpg" 
    date: "Oct 2022 - Today"
    description: "Consultant @ <a href=\"https://www.google.com/url?sa=i&url=https%3A%2F%2Flogos-world.net%2Fernst-young-logo%2F&psig=AOvVaw05WZXscA6CRnQSvHPqH7_o&ust=1674816531131000&source=images&cd=vfe&ved=0CA8QjRxqFwoTCICp7vSH5fwCFQAAAAAdAAAAABAE" target=\"_blank\">EY</a>"
  - image: "/img/timeline/tcs_logo.jpg" 
    date: "June 2018 - Sep 2021"
    description: "Java Developer @ <a href=\"https://en.wikipedia.org/wiki/Tata_Consultancy_Services\" target=\"_blank\">Tata Consultancy Services</a>"
  - image: "/img/timeline/SimpleWay2Code.jpg"
    date: "October 2017"
    description: "Created <a href=\"https://www.simpleway2code.me/p/c-program.html\" target=\"_blank\">SimpleWay2Code </a> An online portal for Coding Preperation"
  - image: "/img/timeline/coding.jpg"
    date: "February 2015"
    description: "Started coding form Scratch"
  - image: "/img/timeline/education.jpg"
    date: "August 2014 - May 2018"
    description: "Joined Undergraduate program Specialized in <a href=\"https://en.wikipedia.org/wiki/Computer_Science_and_Engineering\" target=\"_blank\"> Computer Science & Engineering</a> "

# First image of the Timeline

timeline-img: "/img/timeline/author.png"

###########
# Contact #
###########

email: "hrishabh0007@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Hrishabh is an awesome person. He lives in India, where he works in an IT Company, also does some freelancing job and sometimes writes Blogs. In his spare time, Hrishabh likes to cook."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "linkedin"
    url: "https://www.linkedin.com/in/hrishabh-kumar/"
  - title: "twitter"
    url: "https://twitter.com/h4rishabh"
  - title: "github"
    url: "https://github.com/h4rishabh"
  - title: "facebook"
    url: "https://facebook.com/hrishabh.bajaj1"
  #  url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  #- title: "bitcoin"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: Hrishabh
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
